### ISSUE TITLE
ticket 2

### ISSUE THREAD

**Issue by OrbicCode** [SchoolOfCode/bc17-w6-d2-workshop-tdd-jka-tech-titans#2]
```[tasklist]
### Tasks
- [ ] Write a new test that checks whether `calculateScrabbleScore` correctly calculates the score for the word `A`.
- [ ] Once you've written the test, run the tests with Vitest.
- [ ] Now add the simplest code you can to the `calculateScrabbleScore` function. Make it return the right score for the word "A" to pass the failing test.
- [ ] Once you've updated the implementation, run the tests again.
- [ ] Look over the code. Make changes to simplify or improve it if you can. When you're done with changes, run the tests again. This checks that your changes didn't break anything.
- [ ] Now repeat steps 1-3 for the remaining single letter words (i.e. `B`, `C`, `D` and so forth up to and including `Z`).
```
